name: ALICIA STURDY
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5770609
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Alicia Sturdy Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#030303'
    - '#7E7978'
    - '#534241'
    - '#A4A3A2'
  brandStrength: 0.4982079
  lightness: 0.6792115
  saturation: 0.3512545
  rhythmicContrast: 0.5770609
purpose: []
