layout_spectrum: 1
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3512545
  lightness: 0.6792115
  brandStrength: 0.4982079
  brandColors:
    - '#FFFFFF'
    - '#030303'
    - '#7E7978'
    - '#534241'
    - '#A4A3A2'
  rhythmicContrast: 0.5770609
typography_spectrum: 0.5770609
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: ALICIA STURDY
